# See the full yml reference at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: rdm-v2-web

useDotenv: true

plugins:
  - serverless-lift

params:
  production:
    domain: rdm.uq.edu.au
    certificate: arn:aws:acm:us-east-1:test

constructs:
  web:
    domain: ${param:domain}
    certificate: ${param:certificate}
    type: static-website
    path: dist
    extensions: {
      bucket: {
        Properties: {
          PublicAccessBlockConfiguration: {
            BlockPublicPolicy: false,
          }
        }
      }
    }

resources:
  Resources:
    Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: A123456 # Your HostedZoneId
        Name: ${param:domain}
        Type: A
        AliasTarget:
          HostedZoneId: A1223456 # Cloudfront Route53 HostedZoneId. This does not change.
          DNSName: ${construct:web.cname}

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
